### ISSUE TITLE
Release v2.4 палится антивирусом виндовым и говорит что это вирус...

### ISSUE THREAD

**Issue by exxxt4zy** [MaxNagibator/SpaceSnoop#7]

**Comment by MaxNagibator** [comment]
не исключено, подумаем.

**Comment by TheVSAKeeper** [comment]
Можно не беспокоиться. Вирусов нет. Отчеты VirusTotal для [архива](https://www.virustotal.com/gui/file/30567acf88117092732680577840bda4781267203e6183037b9383447cbb716b) и [exe файла](https://www.virustotal.com/gui/file/e3521ee5a880f330b314238b0d9d5b99ede93ca49a4caa71798a308ce258fb00).

**Comment by MaxNagibator** [comment]
ну виросов нет, у нас всё качественно

**Comment by MaxNagibator** [comment]
ну виросов нет, у нас всё качественно
